/**
 * 花卉知识库种子数据（v1：60 种国内常见花）
 * 说明：
 * - id 作为云数据库文档 _id，用于稳定性导入
 * - rarity: common 常见 / rare 少见 / epic 珍稀 / legendary 传说
 * - bloomSeasons: 花期，取值 春/夏/秋/冬（大致区间，供图鉴分组与成就判定）
 * - synonyms: 别名，用于百度识别结果匹配
 * - illustrationFileID: 水彩插画（云存储 fileID 或 https URL），内容生产后填写
 */
module.exports = [
  {
    id: 'yueji', cnName: '月季', latinName: 'Rosa chinensis', family: '蔷薇科', genus: '蔷薇属',
    rarity: 'common', bloomSeasons: ['春', '夏', '秋'], colors: ['红', '粉', '黄', '白', '橙'],
    description: '被称为“花中皇后”，花期极长，几乎月月开花，是城市绿化里最常见的身影。',
    features: '茎有刺，叶缘有锯齿，花多单生或数朵聚生，香气淡雅。',
    flowerLanguage: '等待有希望的希望，代表幸福与光荣。',
    careTips: '喜光喜肥，及时修剪残花可促进连续开花。',
    distribution: '原产中国，现遍植世界各地。',
    funFact: '月季、玫瑰、蔷薇三姐妹常被混淆，切花店里卖的“玫瑰”大多是现代月季。',
    synonyms: ['月月红', '四季花', '胜春'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yueji.jpg', enabled: true
  },
  {
    id: 'meigui', cnName: '玫瑰', latinName: 'Rosa rugosa', family: '蔷薇科', genus: '蔷薇属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['红', '粉', '白'],
    description: '传统名花，枝条多刺，花大色艳，是爱情与浪漫的经典象征。',
    features: '小枝密生绒毛与皮刺，叶面有明显皱纹，花瓣可食用可制酱。',
    flowerLanguage: '热烈的爱、美好。',
    careTips: '耐寒耐旱，需充足光照，注意防治蚜虫。',
    distribution: '原产中国华北、东北，各地广泛栽培。',
    funFact: '真正的玫瑰每年只在初夏开一季，花店里的“玫瑰”其实是切花月季。',
    synonyms: ['刺玫花', '徘徊花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/meigui.jpg', enabled: true
  },
  {
    id: 'meihua', cnName: '梅花', latinName: 'Prunus mume', family: '蔷薇科', genus: '李属',
    rarity: 'rare', bloomSeasons: ['冬', '春'], colors: ['红', '粉', '白'],
    description: '岁寒三友之一，凌寒开放，与兰、竹、菊并称“花中四君子”。',
    features: '先花后叶，花梗极短，具梅香，枝条光滑无刺。',
    flowerLanguage: '坚韧、高洁、凌寒独放。',
    careTips: '喜冷凉气候，忌涝，盆栽需注意控水促花。',
    distribution: '原产中国南方，长江流域及以南栽培最多。',
    funFact: '南京梅花山、武汉东湖梅园都是著名的赏梅胜地。',
    synonyms: ['春梅', '干枝梅'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/meihua.jpg', enabled: true
  },
  {
    id: 'taohua', cnName: '桃花', latinName: 'Prunus persica', family: '蔷薇科', genus: '桃属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['粉', '红', '白'],
    description: '春回大地的信使，桃之夭夭，灼灼其华，是古典诗词里的常客。',
    features: '先叶开放，花瓣5枚，单瓣或重瓣，花叶同放于枝条上。',
    flowerLanguage: '爱情、好运、春天的祝福。',
    careTips: '喜光耐旱，忌积水，花期约两周。',
    distribution: '原产中国，遍植全国，著名产地有北京平谷、西藏林芝。',
    funFact: '“桃花运”一词让桃花成了姻缘的象征，林芝雪山桃花每年吸引大量游客。',
    synonyms: ['碧桃'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/taohua.jpg', enabled: true
  },
  {
    id: 'yinghua', cnName: '樱花', latinName: 'Prunus serrulata', family: '蔷薇科', genus: '樱属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['粉', '白'],
    description: '春季最浪漫的风景，花瓣纷飞如雪，花期虽短却惊艳。',
    features: '伞形花序，花瓣先端有缺口（花裂），花梗细长。',
    flowerLanguage: '生命、热烈、纯洁、高尚。',
    careTips: '喜温暖湿润，花期怕大风大雨，须根浅忌重剪。',
    distribution: '原产中国及日本，武汉大学、无锡鼋头渚为国内赏樱名地。',
    funFact: '樱花按开放时间有早樱、中樱、晚樱之分，可接力开放一个月。',
    synonyms: ['山樱花', '日本樱花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yinghua.jpg', enabled: true
  },
  {
    id: 'lihua', cnName: '梨花', latinName: 'Pyrus bretschneideri', family: '蔷薇科', genus: '梨属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['白'],
    description: '忽如一夜春风来，千树万树梨花开，洁白似雪的花海盛景。',
    features: '花白色，花药紫红色，先叶开放或花叶同放。',
    flowerLanguage: '纯真、陪伴、守候。',
    careTips: '喜光，需异花授粉，花期注意防倒春寒。',
    distribution: '原产中国，华北、西北、西南梨产区常见。',
    funFact: '河北赵县“梨花节”闻名全国，梨树开花时如覆雪。',
    synonyms: ['白梨'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/lihua.jpg', enabled: true
  },
  {
    id: 'haitang', cnName: '海棠', latinName: 'Malus spectabilis', family: '蔷薇科', genus: '苹果属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['粉', '红'],
    description: '海棠花姿潇洒，花开似锦，自古是雅俗共赏的名花。',
    features: '伞形总状花序，花瓣粉红，花蕾期颜色更深，花与叶同放。',
    flowerLanguage: '游子思乡、离愁别绪、温和美丽。',
    careTips: '喜光耐寒，花期控水可延长观赏时间。',
    distribution: '原产中国，华北、华东庭院常见。',
    funFact: '西府海棠、垂丝海棠、贴梗海棠是常见的栽培观赏种类。',
    synonyms: ['海棠花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/haitang.jpg', enabled: true
  },
  {
    id: 'mudan', cnName: '牡丹', latinName: 'Paeonia suffruticosa', family: '芍药科', genus: '芍药属',
    rarity: 'epic', bloomSeasons: ['春'], colors: ['红', '粉', '白', '紫'],
    description: '花中之王，国色天香，雍容华贵，是富贵的象征。',
    features: '落叶灌木，花大色艳，单生枝顶，有单瓣、重瓣等多种花型。',
    flowerLanguage: '圆满、浓情、富贵吉祥。',
    careTips: '喜凉怕热，忌积水，春分前后注意病虫害防治。',
    distribution: '原产中国，洛阳、菏泽为两大栽培中心。',
    funFact: '“唯有牡丹真国色，花开时节动京城”，牡丹与芍药同科，牡丹为木本、芍药为草本。',
    synonyms: ['洛阳花', '富贵花', '木芍药'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/mudan.jpg', enabled: true
  },
  {
    id: 'shaoyao', cnName: '芍药', latinName: 'Paeonia lactiflora', family: '芍药科', genus: '芍药属',
    rarity: 'epic', bloomSeasons: ['春', '夏'], colors: ['粉', '红', '白'],
    description: '花中宰相，五月花神，与牡丹并称“花中二绝”。',
    features: '多年生草本，花大而香，茎直立，叶先端常三裂。',
    flowerLanguage: '依依惜别、情有所钟。',
    careTips: '喜阳光充足，秋植最佳，花前适当疏蕾花朵更大。',
    distribution: '原产中国北部，各地均有栽培。',
    funFact: '古人有“立夏三朝看芍药”之说，芍药又称“将离”，常作临别赠花。',
    synonyms: ['将离', '没骨花', '离草'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/shaoyao.jpg', enabled: true
  },
  {
    id: 'hehua', cnName: '荷花', latinName: 'Nelumbo nucifera', family: '莲科', genus: '莲属',
    rarity: 'rare', bloomSeasons: ['夏'], colors: ['粉', '白'],
    description: '出淤泥而不染，濯清涟而不妖，是盛夏池塘的主角。',
    features: '水生草本，叶盾状圆形挺出水面，花大清香，藕与莲子皆可食。',
    flowerLanguage: '清白、坚贞、纯洁、信仰。',
    careTips: '喜光喜温，水深宜保持 30-80cm，花期需充足日照。',
    distribution: '原产亚洲热带及温带，中国各地湖塘广布。',
    funFact: '莲子是植物界长寿冠军，千年古莲子仍能发芽开花。',
    synonyms: ['莲花', '芙蕖', '水芙蓉', '菡萏'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/hehua.jpg', enabled: true
  },
  {
    id: 'shuilian', cnName: '睡莲', latinName: 'Nymphaea tetragona', family: '睡莲科', genus: '睡莲属',
    rarity: 'epic', bloomSeasons: ['夏', '秋'], colors: ['白', '粉', '黄'],
    description: '浮在水面的“水中女神”，白天绽放、夜晚闭合，宁静优雅。',
    features: '叶浮水面，叶缘有深裂，花生于花梗顶端，多昼开夜合。',
    flowerLanguage: '纯洁、宁静、返璞归真。',
    careTips: '喜阳光充足，耐热，冬季需保护根茎越冬。',
    distribution: '原产中国东北、华北，现世界广泛栽培。',
    funFact: '莫奈晚年痴迷睡莲，画了约 250 幅《睡莲》系列作品。',
    synonyms: ['子午莲'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/shuilian.jpg', enabled: true
  },
  {
    id: 'juhua', cnName: '菊花', latinName: 'Chrysanthemum morifolium', family: '菊科', genus: '菊属',
    rarity: 'common', bloomSeasons: ['秋'], colors: ['黄', '白', '红', '紫'],
    description: '花中四君子之一，秋日主角，傲霜开放，品种多达数千。',
    features: '头状花序，舌状花与管状花组成，花型花色极其丰富。',
    flowerLanguage: '清净、高洁、怀念、长寿。',
    careTips: '短日照植物，喜凉爽，秋季花芽分化后注意防霜。',
    distribution: '原产中国，栽培历史超过三千年。',
    funFact: '中国传统节日重阳节有赏菊、饮菊花酒习俗。',
    synonyms: ['秋菊', '黄花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/juhua.jpg', enabled: true
  },
  {
    id: 'guihua', cnName: '桂花', latinName: 'Osmanthus fragrans', family: '木犀科', genus: '木犀属',
    rarity: 'rare', bloomSeasons: ['秋'], colors: ['黄', '橙'],
    description: '八月桂花香，花小如金粟，香飘十里，是秋日记忆的味道。',
    features: '常绿乔木，花簇生叶腋，香气浓郁，果为紫黑色核果。',
    flowerLanguage: '收获、吉祥、永伴佳人。',
    careTips: '喜温暖湿润，耐半阴，花期前增施磷钾肥可促进开花。',
    distribution: '原产中国西南，长江流域以南广泛栽培。',
    funFact: '桂花可制桂花糕、桂花茶、桂花酒，“蟾宫折桂”象征登科中举。',
    synonyms: ['木犀', '九里香', '金桂', '丹桂', '银桂'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/guihua.jpg', enabled: true
  },
  {
    id: 'dujuan', cnName: '杜鹃花', latinName: 'Rhododendron simsii', family: '杜鹃花科', genus: '杜鹃花属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['红', '粉', '紫', '白'],
    description: '满山红遍的“花中西施”，山野间最常见的艳丽春花。',
    features: '花冠漏斗形，2-6 朵簇生枝顶，叶纸质，密被糙伏毛。',
    flowerLanguage: '永远属于你、节制、喜悦。',
    careTips: '喜酸性土壤，忌碱性水土，花期避免烈日暴晒。',
    distribution: '原产中国，长江流域及以南丘陵常见。',
    funFact: '相传杜鹃花是杜鹃鸟啼血染红，贵州毕节有世界最大野生杜鹃林。',
    synonyms: ['映山红', '山石榴', '满山红'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/dujuan.jpg', enabled: true
  },
  {
    id: 'shanchahua', cnName: '山茶花', latinName: 'Camellia japonica', family: '山茶科', genus: '山茶属',
    rarity: 'rare', bloomSeasons: ['冬', '春'], colors: ['红', '粉', '白'],
    description: '冬春之交的“花中娇客”，花瓣层层叠叠，端庄华美。',
    features: '常绿灌木，叶革质光亮，花大色艳，品种繁多。',
    flowerLanguage: '理想的爱、谦让、可爱。',
    careTips: '喜半阴湿润环境，喜酸性土，花期忌大肥大水。',
    distribution: '原产中国东部及日本，云南、浙江、四川最盛。',
    funFact: '《天龙八部》中大理段氏珍爱茶花，现实中云南山茶同样名扬天下。',
    synonyms: ['茶花', '海石榴'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/shanchahua.jpg', enabled: true
  },
  {
    id: 'yulan', cnName: '玉兰', latinName: 'Magnolia denudata', family: '木兰科', genus: '木兰属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['白'],
    description: '早春先花后叶，满树白花如雪似玉，幽香淡雅。',
    features: '落叶乔木，花被片 9 枚，白色基部常带粉晕，杯状盛开。',
    flowerLanguage: '报恩、纯洁、高洁。',
    careTips: '喜光稍耐阴，肉质根怕积水，移栽宜在春季。',
    distribution: '原产中国中部，现南北庭院广植。',
    funFact: '上海、连云港、保定等城市把玉兰作为市花。',
    synonyms: ['白玉兰', '望春花', '玉堂春'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yulan.jpg', enabled: true
  },
  {
    id: 'zhizihua', cnName: '栀子花', latinName: 'Gardenia jasminoides', family: '茜草科', genus: '栀子属',
    rarity: 'common', bloomSeasons: ['夏'], colors: ['白'],
    description: '洁白芬芳的夏日花，香浓如奶油，是老一辈记忆里的庭院花。',
    features: '花单生枝顶或叶腋，白色后渐黄，叶对生革质光亮。',
    flowerLanguage: '永恒的爱、一生的守候。',
    careTips: '喜酸性土壤，缺铁易黄叶，夏季需保持盆土湿润。',
    distribution: '原产中国长江流域以南，各地常见盆栽。',
    funFact: '果实名“栀子”，是传统天然黄色染料，也是常见中药材。',
    synonyms: ['栀子', '黄栀子', '山栀'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/zhizihua.jpg', enabled: true
  },
  {
    id: 'molihua', cnName: '茉莉花', latinName: 'Jasminum sambac', family: '木犀科', genus: '素馨属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['白'],
    description: '好一朵美丽的茉莉花，洁白清香，是国民度最高的花香之一。',
    features: '常绿灌木，花冠白色，单瓣或重瓣，香气浓郁，聚伞花序。',
    flowerLanguage: '忠贞、尊敬、清纯。',
    careTips: '喜温暖湿润，怕寒冷，花蕾期控水可增香。',
    distribution: '原产印度，中国南方广泛栽培，福州茉莉花茶闻名。',
    funFact: '茉莉花茶以茉莉鲜花窨制，一公斤特级茶需用花数公斤。',
    synonyms: ['茉莉'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/molihua.jpg', enabled: true
  },
  {
    id: 'baihe', cnName: '百合', latinName: 'Lilium brownii', family: '百合科', genus: '百合属',
    rarity: 'rare', bloomSeasons: ['夏'], colors: ['白', '粉', '黄', '橙'],
    description: '百年好合，花香清雅，是婚礼与祝福场合的经典鲜花。',
    features: '花大呈喇叭形，6 枚花被片，雄蕊显著，鳞茎可食。',
    flowerLanguage: '百年好合、纯洁、庄严。',
    careTips: '喜凉爽光照充足，忌高温高湿，盆栽需排水良好。',
    distribution: '原产中国，甘肃兰州鲜百合与各地观赏百合皆有名。',
    funFact: '可食用百合与观赏百合品种不同，观赏百合鳞茎不宜食用。',
    synonyms: ['百合花', '山百合'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/baihe.jpg', enabled: true
  },
  {
    id: 'yujinxiang', cnName: '郁金香', latinName: 'Tulipa gesneriana', family: '百合科', genus: '郁金香属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['红', '黄', '粉', '紫', '白'],
    description: '荷兰国花，亭亭玉立，色彩缤纷，是春天花田的颜值担当。',
    features: '花单生茎顶，杯状，直立，叶带状披针形，鳞茎圆整。',
    flowerLanguage: '博爱、高雅、富贵、能干。',
    careTips: '喜冷凉，忌酷暑，种球需低温春化才能开花。',
    distribution: '原产地中海沿岸及中亚，中国新疆伊犁、云南等地大量栽培。',
    funFact: '17 世纪荷兰曾因郁金香种球掀起“郁金香狂热”，堪称最早的泡沫经济。',
    synonyms: ['洋荷花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yujinxiang.jpg', enabled: true
  },
  {
    id: 'xiangrikui', cnName: '向日葵', latinName: 'Helianthus annuus', family: '菊科', genus: '向日葵属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['黄'],
    description: '永远面向太阳的乐观之花，夏日田野最热烈的金色。',
    features: '头状花序硕大，花序随光转动的现象主要发生在幼嫩期。',
    flowerLanguage: '沉默的爱、忠诚、向阳而生。',
    careTips: '喜光耐旱，花盘随成熟渐重，需支撑防倒伏。',
    distribution: '原产北美，中国各地油用与观赏栽培广泛。',
    funFact: '向日葵花盘由上千朵小花组成，中间的管状花结出葵花籽。',
    synonyms: ['太阳花', '葵花', '向阳花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/xiangrikui.jpg', enabled: true
  },
  {
    id: 'youcaihua', cnName: '油菜花', latinName: 'Brassica napus', family: '十字花科', genus: '芸薹属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['黄'],
    description: '春天的金色海洋，山野梯田之间最壮观的农业花海。',
    features: '十字形花冠，四片黄色花瓣，总状花序，植株高约 1 米。',
    flowerLanguage: '加油、春天、希望。',
    careTips: '喜凉耐寒，花期约 20-30 天，观赏时请勿踩踏田垄。',
    distribution: '中国长江流域及西北广泛种植，江西婺源、青海门源最负盛名。',
    funFact: '油菜花不仅好看，菜籽榨油是国产食用油的重要来源。',
    synonyms: ['油菜', '芸薹', '菜花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/youcaihua.jpg', enabled: true
  },
  {
    id: 'xunyicao', cnName: '薰衣草', latinName: 'Lavandula angustifolia', family: '唇形科', genus: '薰衣草属',
    rarity: 'rare', bloomSeasons: ['夏'], colors: ['紫'],
    description: '紫色浪漫的代名词，香气舒缓助眠，是香草世界的明星。',
    features: '穗状花序，蓝紫色小花密集，叶线形灰绿色，全株具芳香。',
    flowerLanguage: '等待爱情、宁静、感恩。',
    careTips: '喜干燥阳光充足，怕湿热，土壤需排水良好。',
    distribution: '原产地中海沿岸，中国新疆伊犁被称为“中国薰衣草之乡”。',
    funFact: '伊犁与法国普罗旺斯同处北纬 43° 左右，都是薰衣草黄金产区。',
    synonyms: ['薰衣草'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/xunyicao.jpg', enabled: true
  },
  {
    id: 'bosijv', cnName: '波斯菊', latinName: 'Cosmos bipinnatus', family: '菊科', genus: '秋英属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['粉', '白', '紫'],
    description: '轻盈的格桑花，细碎叶片配粉紫花朵，随微风摇曳生姿。',
    features: '叶二回羽状深裂成丝状，头状花序生于细长花梗顶端。',
    flowerLanguage: '怜惜眼前人、少女之心、自由。',
    careTips: '耐瘠薄，怕肥怕涝，种子自播能力强，一片即可成花海。',
    distribution: '原产墨西哥，中国各地公园、路边常见。',
    funFact: '西藏常把波斯菊称为“格桑花”，其实格桑花在藏语中泛指高原野花。',
    synonyms: ['秋英', '格桑花', '大波斯菊'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/bosijv.jpg', enabled: true
  },
  {
    id: 'chuju', cnName: '雏菊', latinName: 'Bellis perennis', family: '菊科', genus: '雏菊属',
    rarity: 'common', bloomSeasons: ['春', '秋'], colors: ['白', '粉', '红'],
    description: '小巧可爱的迷你菊花，草坪上星星点点，童真治愈。',
    features: '植株低矮丛生，头状花序单生，舌状花白色或粉色。',
    flowerLanguage: '天真、和平、深藏在心底的爱。',
    careTips: '喜冷凉，耐寒不耐热，夏季高温常休眠。',
    distribution: '原产欧洲，中国各地园林地被广泛应用。',
    funFact: '《雏菊》也是法国电影《这个杀手不太冷》女主角的名字来源。',
    synonyms: ['延命菊', '小雏菊'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/chuju.jpg', enabled: true
  },
  {
    id: 'shicheju', cnName: '矢车菊', latinName: 'Centaurea cyanus', family: '菊科', genus: '矢车菊属',
    rarity: 'rare', bloomSeasons: ['春', '夏'], colors: ['蓝', '紫', '粉', '白'],
    description: '德国国花，标志性的蓝色花朵如矢车菊般优雅清澈。',
    features: '头状花序边缘小花呈漏斗状蓝紫色，茎叶被白色绵毛。',
    flowerLanguage: '遇见幸福、温柔可爱、单相思。',
    careTips: '喜阳光充足，直根性较强，移栽需带土球。',
    distribution: '原产欧洲，中国庭园与切花栽培渐多。',
    funFact: '拿破仑曾用矢车菊汁蘸面包果腹，因此它也被称为“皇帝之花”。',
    synonyms: ['蓝芙蓉'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/shicheju.jpg', enabled: true
  },
  {
    id: 'kangnaixin', cnName: '康乃馨', latinName: 'Dianthus caryophyllus', family: '石竹科', genus: '石竹属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['粉', '红', '白', '黄'],
    description: '母爱之花，母亲节的主角，端庄芬芳的切花之王。',
    features: '花单生或数朵聚生，花瓣边缘锯齿状，茎节膨大，叶线形。',
    flowerLanguage: '母爱、温馨、真情。',
    careTips: '喜凉爽干燥，怕涝，温室栽培可全年供花。',
    distribution: '原产地中海沿岸，中国云南、辽宁为主要产区。',
    funFact: '1934 年美国正式发行母亲节邮票，图案就是康乃馨。',
    synonyms: ['香石竹'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/kangnaixin.jpg', enabled: true
  },
  {
    id: 'mantianxing', cnName: '满天星', latinName: 'Gypsophila paniculata', family: '石竹科', genus: '丝石竹属',
    rarity: 'common', bloomSeasons: ['夏'], colors: ['白', '粉'],
    description: '满天繁星的浪漫配角，细碎白花如雾如纱，百搭花束。',
    features: '圆锥状聚伞花序疏散，花极小，白色居多，茎纤细分叉多。',
    flowerLanguage: '思念、清纯、梦境、配角。',
    careTips: '喜干燥凉爽，怕湿涝，花期控制水肥可保持花姿。',
    distribution: '原产欧洲、亚洲，中国云南广泛种植。',
    funFact: '满天星干花与鲜花同样美观，是花艺中的“填充大师”。',
    synonyms: ['圆锥石头花', '丝石竹', '霞草'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/mantianxing.jpg', enabled: true
  },
  {
    id: 'yuanwei', cnName: '鸢尾', latinName: 'Iris tectorum', family: '鸢尾科', genus: '鸢尾属',
    rarity: 'epic', bloomSeasons: ['春', '夏'], colors: ['蓝', '紫', '白', '黄'],
    description: '花瓣如鸢鸟之尾，蓝色系尤显神秘高贵，梵高笔下的经典。',
    features: '花被片 6 枚，外轮三枚下垂、内轮三枚直立，根状茎匍匐。',
    flowerLanguage: '想念你、爱的使者、光明与自由。',
    careTips: '喜阳光充足，耐半阴，忌积水，分株繁殖。',
    distribution: '原产中国中部及日本，各地庭园常见。',
    funFact: '法国国花香根鸢尾与画家莫奈吉维尼花园的鸢尾同样著名。',
    synonyms: ['蓝蝴蝶', '扁竹花', '乌鸢'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yuanwei.jpg', enabled: true
  },
  {
    id: 'chunlan', cnName: '春兰', latinName: 'Cymbidium goeringii', family: '兰科', genus: '兰属',
    rarity: 'epic', bloomSeasons: ['春'], colors: ['绿', '黄'],
    description: '中国兰之首，幽香清远，叶姿飘逸，君子之花。',
    features: '一秆一花或两花，花被片淡绿黄，唇瓣有紫红斑点，香气幽雅。',
    flowerLanguage: '高洁、贤德、美好。',
    careTips: '喜半阴通风，植料需疏松透气，忌暴晒积水。',
    distribution: '原产中国长江流域及以南山区。',
    funFact: '兰花的香气来自特定化合物，不同品种香气各异，名品价格不菲。',
    synonyms: ['兰花', '山兰', '草兰', '朵朵香'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/chunlan.jpg', enabled: true
  },
  {
    id: 'hudielan', cnName: '蝴蝶兰', latinName: 'Phalaenopsis aphrodite', family: '兰科', genus: '蝴蝶兰属',
    rarity: 'epic', bloomSeasons: ['冬', '春'], colors: ['紫', '粉', '白', '黄'],
    description: '如蝴蝶翩翩起舞的年宵花之王，花期长达数月。',
    features: '花茎拱形，花朵排列成串，花瓣宽阔，形似蝴蝶。',
    flowerLanguage: '幸福向你飞来、我爱你。',
    careTips: '附生兰，喜温暖湿润，忌积水，用树皮水苔栽培。',
    distribution: '原产亚洲热带，中国台湾、广东大规模产业化种植。',
    funFact: '蝴蝶兰老茎切下后叶腋可萌生高芽，一株可繁育多株。',
    synonyms: ['蝶兰'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/hudielan.jpg', enabled: true
  },
  {
    id: 'junzilan', cnName: '君子兰', latinName: 'Clivia miniata', family: '石蒜科', genus: '君子兰属',
    rarity: 'epic', bloomSeasons: ['冬', '春'], colors: ['橙', '黄'],
    description: '叶片如剑、花团似火，端庄大气，备受北方花友喜爱。',
    features: '叶带状二列互生，伞形花序顶生，花漏斗状橙红色。',
    flowerLanguage: '高贵、君子之风、丰盛。',
    careTips: '喜散射光，忌强光直射，冬季需温差促进开花。',
    distribution: '原产南非，中国长春为君子兰培育重镇。',
    funFact: '君子兰在 1980 年代长春曾创下天价交易，被称为“绿色金条”。',
    synonyms: ['大花君子兰'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/junzilan.jpg', enabled: true
  },
  {
    id: 'shuixian', cnName: '水仙', latinName: 'Narcissus tazetta', family: '石蒜科', genus: '水仙属',
    rarity: 'rare', bloomSeasons: ['冬', '春'], colors: ['白', '黄'],
    description: '凌波仙子，清水一盆便绽芳华，是春节最应景的室内花。',
    features: '鳞茎卵球形，花冠白色、副冠黄色呈杯状，具清香。',
    flowerLanguage: '思念、团圆、万事如意。',
    careTips: '水培注意换水，温度 10-20℃ 最宜，光照不足易徒长。',
    distribution: '原产地中海沿岸，中国福建漳州为著名产区。',
    funFact: '漳州水仙以“三桄”雕刻工艺闻名，能开出多层花头。',
    synonyms: ['中国水仙', '金盏银台'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/shuixian.jpg', enabled: true
  },
  {
    id: 'fengxiaozi', cnName: '风信子', latinName: 'Hyacinthus orientalis', family: '天门冬科', genus: '风信子属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['紫', '蓝', '粉', '白'],
    description: '花序如串铃，色彩饱和浓郁，早春花市里最亮眼的球根花。',
    features: '总状花序密集，小花钟形，叶带状肥厚，鳞茎球形。',
    flowerLanguage: '点燃生命之火、幸福、喜悦。',
    careTips: '喜冷凉，种球需低温春化，水培时水位勿触鳞茎底部。',
    distribution: '原产东南欧及地中海东部，中国各地冬春栽培。',
    funFact: '风信子花香极其浓郁，密闭房间摆放多株可能“香到上头”。',
    synonyms: ['洋水仙', '五色水仙'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/fengxiaozi.jpg', enabled: true
  },
  {
    id: 'ziluolan', cnName: '紫罗兰', latinName: 'Matthiola incana', family: '十字花科', genus: '紫罗兰属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['紫', '粉', '白'],
    description: '欧洲名花，花色以紫为贵，香气温婉，是切花常客。',
    features: '总状花序长而密，花瓣四枚，单瓣或重瓣，叶灰绿色被毛。',
    flowerLanguage: '永恒的美与爱、质朴、美德。',
    careTips: '喜冷凉，耐寒怕热，夏季高温易凋谢。',
    distribution: '原产欧洲南部，中国各地栽培。',
    funFact: '拿破仑的皇后约瑟芬最爱紫罗兰，甚至以它为政治暗号。',
    synonyms: ['草桂花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/ziluolan.jpg', enabled: true
  },
  {
    id: 'sanseqin', cnName: '三色堇', latinName: 'Viola tricolor', family: '堇菜科', genus: '堇菜属',
    rarity: 'common', bloomSeasons: ['春', '秋'], colors: ['紫', '黄', '白'],
    description: '花脸猫般的三色花瓣，歪头浅笑，是花坛最俏皮的小精灵。',
    features: '花通常三色，如猫脸状，花瓣 5 枚，茎生叶有锯齿。',
    flowerLanguage: '沉思、快乐、请思念我。',
    careTips: '喜凉爽，耐寒不耐热，秋播春花效果好。',
    distribution: '原产欧洲，中国各地花坛、地被广泛使用。',
    funFact: '三色堇是冰岛国花，也是香草“角堇”的近亲。',
    synonyms: ['蝴蝶花', '猫儿脸', '人面花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/sanseqin.jpg', enabled: true
  },
  {
    id: 'qianniuhua', cnName: '牵牛花', latinName: 'Ipomoea nil', family: '旋花科', genus: '牵牛属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['紫', '蓝', '粉', '红'],
    description: '清晨绽放的喇叭花，朝颜夕谢，藤蔓缠绕充满田园气息。',
    features: '花冠漏斗状似喇叭，茎左旋缠绕，叶心形或三裂。',
    flowerLanguage: '爱情永固、冷静、虚幻。',
    careTips: '喜光耐热，种前浸种易发芽，盆栽需搭架牵引。',
    distribution: '原产亚洲热带，中国南北乡野常见。',
    funFact: '牵牛花日语称“朝颜”，清晨开花、午后凋谢，花期仅半天。',
    synonyms: ['喇叭花', '牵牛', '朝颜'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/qianniuhua.jpg', enabled: true
  },
  {
    id: 'jinyinhua', cnName: '金银花', latinName: 'Lonicera japonica', family: '忍冬科', genus: '忍冬属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['白', '黄'],
    description: '初开雪白、后转金黄，一藤双色，香气清甜，清热解毒。',
    features: '藤本，花成对生于叶腋，花冠二唇形，先白后黄。',
    flowerLanguage: '全心全意把爱奉献给你、鸳鸯成对。',
    careTips: '喜光耐荫耐旱，生长迅速，需及时修剪。',
    distribution: '原产中国，南北各省均有分布。',
    funFact: '金银花是中国著名中药材“银翘解毒片”的核心成分之一。',
    synonyms: ['忍冬', '鸳鸯藤', '二花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/jinyinhua.jpg', enabled: true
  },
  {
    id: 'yingchunhua', cnName: '迎春花', latinName: 'Jasminum nudiflorum', family: '木犀科', genus: '素馨属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['黄'],
    description: '迎得春来非自足，百花千卉共芬芳，最早的报春使者。',
    features: '落叶灌木，先花后叶，花单生于去年枝上，金黄色 6 裂。',
    flowerLanguage: '相爱到永远、活力、希望。',
    careTips: '喜光耐寒，萌芽力强，花后重剪可促分枝。',
    distribution: '原产中国，秦岭以南及华北庭园常见。',
    funFact: '迎春花、连翘同为早春黄花，区别在迎春枝条四棱、连翘中空。',
    synonyms: ['迎春', '金腰带', '黄素馨'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yingchunhua.jpg', enabled: true
  },
  {
    id: 'lianqiao', cnName: '连翘', latinName: 'Forsythia suspensa', family: '木犀科', genus: '连翘属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['黄'],
    description: '早春满枝金黄，四瓣小花比迎春更舒展，公园路旁成片金黄。',
    features: '灌木，枝开展下垂、节间中空，花冠 4 裂，先叶开放。',
    flowerLanguage: '指导、永恒。',
    careTips: '喜光耐旱，适应性极强，几乎无需特殊养护。',
    distribution: '原产中国，华北、华中、西北常见。',
    funFact: '连翘果入药，是“双黄连口服液”名称里“连”字的来源。',
    synonyms: ['一串金', '黄金条'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/lianqiao.jpg', enabled: true
  },
  {
    id: 'ziteng', cnName: '紫藤', latinName: 'Wisteria sinensis', family: '豆科', genus: '紫藤属',
    rarity: 'epic', bloomSeasons: ['春'], colors: ['紫'],
    description: '垂如瀑布的紫色花串，架下漫步如入梦境，古典园林必备。',
    features: '木质藤本，总状花序下垂，蝶形花蓝紫色，荚果被绒毛。',
    flowerLanguage: '沉迷的爱、醉人的恋情、依依的思念。',
    careTips: '喜光耐寒，根系深扎，需坚固棚架支撑。',
    distribution: '原产中国，自古庭园栽培，日本京都紫藤隧道闻名。',
    funFact: '紫藤老桩可存活百年以上，上海嘉定古猗园有数百年古藤。',
    synonyms: ['藤萝', '朱藤'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/ziteng.jpg', enabled: true
  },
  {
    id: 'mumianhua', cnName: '木棉花', latinName: 'Bombax ceiba', family: '木棉科', genus: '木棉属',
    rarity: 'rare', bloomSeasons: ['春'], colors: ['红'],
    description: '英雄花，开时满树火红不见叶，落花掷地有声，岭南春日的图腾。',
    features: '落叶大乔木，花红色五瓣，肉质，先花后叶，树干基部有板根。',
    flowerLanguage: '英雄气概、珍惜眼前人。',
    careTips: '喜光喜暖，忌积水，华南露地栽培，北方需温室。',
    distribution: '原产亚洲热带，中国华南、西南常见，广州满城皆植。',
    funFact: '广州人以木棉为市花，木棉絮可作枕芯，干花可煲汤入药。',
    synonyms: ['木棉', '红棉', '攀枝花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/mumianhua.jpg', enabled: true
  },
  {
    id: 'fenghuangmu', cnName: '凤凰木', latinName: 'Delonix regia', family: '豆科', genus: '凤凰木属',
    rarity: 'rare', bloomSeasons: ['夏'], colors: ['红'],
    description: '叶如飞凰之羽、花若丹凤之冠，盛夏南国最炽烈的红色。',
    features: '二回羽状复叶，总状花序鲜红色带黄晕，荚果木质带状。',
    flowerLanguage: '火热、思念、离别。',
    careTips: '喜高温强光，怕霜冻，花期前后控水可促花。',
    distribution: '原产马达加斯加，中国华南、西南广为栽植。',
    funFact: '厦门市树、汕头市花都是凤凰木，毕业季满树火红被称为“毕业花”。',
    synonyms: ['凤凰花', '红花楹', '火树'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/fenghuangmu.jpg', enabled: true
  },
  {
    id: 'lanhuaying', cnName: '蓝花楹', latinName: 'Jacaranda mimosifolia', family: '紫葳科', genus: '蓝花楹属',
    rarity: 'epic', bloomSeasons: ['春', '夏'], colors: ['蓝', '紫'],
    description: '蓝紫色的梦幻花雾，落花铺成花毯，是近年最火的网红花树。',
    features: '落叶乔木，二回羽状复叶，圆锥花序蓝紫色，钟状花冠。',
    flowerLanguage: '宁静、深远、在绝望中等待爱情。',
    careTips: '喜温暖阳光，怕霜冻，花期忌强剪。',
    distribution: '原产南美洲，中国云南、四川、福建、广东等地栽培。',
    funFact: '昆明教场中路与成都的蓝花楹大道，每到花期都是城市级风景线。',
    synonyms: ['蓝楹'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/lanhuaying.jpg', enabled: true
  },
  {
    id: 'jidanhua', cnName: '鸡蛋花', latinName: 'Plumeria rubra', family: '夹竹桃科', genus: '鸡蛋花属',
    rarity: 'rare', bloomSeasons: ['夏', '秋'], colors: ['白', '黄', '粉'],
    description: '花瓣外白内黄如荷包蛋，热带气息扑面，是东南亚的常见行道花。',
    features: '花冠五裂螺旋状排列，聚伞花序，枝干乳汁白色有毒。',
    flowerLanguage: '孕育希望、复活、新生。',
    careTips: '喜高温强光，耐旱，冬季落叶休眠需控水。',
    distribution: '原产美洲热带，中国华南、云南南部常见。',
    funFact: '夏威夷人用鸡蛋花编花环迎宾，簪在耳侧还是单身的信号。',
    synonyms: ['缅栀子', '蛋黄花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/jidanhua.jpg', enabled: true
  },
  {
    id: 'sanjiaomei', cnName: '三角梅', latinName: 'Bougainvillea glabra', family: '紫茉莉科', genus: '叶子花属',
    rarity: 'common', bloomSeasons: ['春', '夏', '秋'], colors: ['红', '粉', '紫', '白'],
    description: '热烈如火的三片“花瓣”其实是苞片，花小而藏其间，南方街头霸主。',
    features: '藤状灌木，苞片 3 枚三角状，色彩艳丽，真正的花很小呈漏斗状。',
    flowerLanguage: '热情、坚韧不拔、没有真爱是一种悲伤。',
    careTips: '喜光耐旱，控水促花是核心技巧，怕寒冷。',
    distribution: '原产南美洲，中国华南、西南广泛栽培，厦门市花。',
    funFact: '三角梅最艳丽的颜色来自苞片而非花瓣，品种可开黄、白、橙等多色。',
    synonyms: ['叶子花', '勒杜鹃', '九重葛', '光叶子花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/sanjiaomei.jpg', enabled: true
  },
  {
    id: 'ziwei', cnName: '紫薇', latinName: 'Lagerstroemia indica', family: '千屈菜科', genus: '紫薇属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['粉', '紫', '白'],
    description: '百日红，盛夏开到深秋，树干光滑，轻挠枝干会微微颤动。',
    features: '圆锥花序顶生，花瓣皱缩，树干表皮片状脱落而光滑。',
    flowerLanguage: '好运、沉迷的爱、雄辩。',
    careTips: '喜光耐旱，花后修剪可二次开花，树干怕磕碰。',
    distribution: '原产亚洲，中国长江流域及以南广植。',
    funFact: '因挠之即动，紫薇又名“痒痒树”，花期为百日之久。',
    synonyms: ['痒痒树', '百日红', '满堂红'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/ziwei.jpg', enabled: true
  },
  {
    id: 'mujin', cnName: '木槿', latinName: 'Hibiscus syriacus', family: '锦葵科', genus: '木槿属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['粉', '紫', '白'],
    description: '朝开暮落却日日新花，温柔而坚韧，韩国国花。',
    features: '落叶灌木，花单生叶腋，花瓣基部常有深色斑，蒴果卵形。',
    flowerLanguage: '温柔的坚持、坚韧、永恒。',
    careTips: '喜光耐旱耐修剪，花量大，篱笆绿化常用。',
    distribution: '原产中国中部，现世界温带广泛栽培。',
    funFact: '木槿花一朵只开一天，但整株能从夏开到秋，故称“无穷花”。',
    synonyms: ['木槿花', '朝开暮落花', '篱障花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/mujin.jpg', enabled: true
  },
  {
    id: 'fusang', cnName: '扶桑', latinName: 'Hibiscus rosa-sinensis', family: '锦葵科', genus: '木槿属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['红', '粉', '黄'],
    description: '大红色的“中国蔷薇”，花瓣如绸缎，是岭南庭院最热烈的花。',
    features: '常绿灌木，花大色艳，花柱显著伸出，全年可见开花。',
    flowerLanguage: '新鲜的恋情、微妙的美、体贴。',
    careTips: '喜光喜暖怕寒，华南露地越冬，华北多盆栽入室。',
    distribution: '原产中国南部，马来西亚、夏威夷等地尊为国花。',
    funFact: '扶桑又名朱槿，“扶桑”也是古书中东方日出之国的名字。',
    synonyms: ['朱槿', '大红花', '佛桑'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/fusang.jpg', enabled: true
  },
  {
    id: 'linglan', cnName: '铃兰', latinName: 'Convallaria majalis', family: '天门冬科', genus: '铃兰属',
    rarity: 'epic', bloomSeasons: ['春'], colors: ['白'],
    description: '一串洁白小铃铛垂于叶间，幽香清雅，是五月新娘的捧花常客。',
    features: '总状花序偏向一侧，花钟形下垂，叶 2-3 枚长椭圆形。',
    flowerLanguage: '幸福归来、纯洁、幸运。',
    careTips: '喜凉爽湿润半阴，忌高温，全株有毒需避儿童宠物。',
    distribution: '原产北半球温带，中国东北、华北山地有野生。',
    funFact: '铃兰全株含强心苷类物质，观赏即可，切勿入口。',
    synonyms: ['君影草', '山谷百合'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/linglan.jpg', enabled: true
  },
  {
    id: 'pugongying', cnName: '蒲公英', latinName: 'Taraxacum officinale', family: '菊科', genus: '蒲公英属',
    rarity: 'common', bloomSeasons: ['春', '秋'], colors: ['黄'],
    description: '草地上的小黄花，成熟后变白色绒球，一吹便乘风远行。',
    features: '叶莲座状羽状分裂，头状花序黄色，瘦果带白色冠毛成球。',
    flowerLanguage: '无法停留的爱、自由、勇敢。',
    careTips: '生命力极强，无需养护，种子随风传播。',
    distribution: '广布中国各地，路边草地最常见。',
    funFact: '蒲公英的“降落伞”冠毛能让种子飘出数公里，堪称风之旅行家。',
    synonyms: ['婆婆丁', '黄花地丁', '蒲公草'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/pugongying.jpg', enabled: true
  },
  {
    id: 'biyanhua', cnName: '彼岸花', latinName: 'Lycoris radiata', family: '石蒜科', genus: '石蒜属',
    rarity: 'epic', bloomSeasons: ['秋'], colors: ['红'],
    description: '花开不见叶、叶生不见花，红如烈焰，凄美而神秘。',
    features: '伞形花序顶生，花被片反卷如龙爪，花后长叶，鳞茎有毒。',
    flowerLanguage: '无尽的思念、绝望的爱、离别。',
    careTips: '喜散射光湿润环境，秋季花后勿挖鳞茎，多年生养护。',
    distribution: '原产中国长江流域，日本、朝鲜也有分布。',
    funFact: '彼岸花学名红花石蒜，因日本佛经故事得名“曼珠沙华”。',
    synonyms: ['红花石蒜', '曼珠沙华', '龙爪花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/biyanhua.jpg', enabled: true
  },
  {
    id: 'hanxiao', cnName: '含笑', latinName: 'Michelia figo', family: '木兰科', genus: '含笑属',
    rarity: 'rare', bloomSeasons: ['春', '夏'], colors: ['白', '黄'],
    description: '花常半开如含笑低眉，香气似熟透的香蕉，甜而不腻。',
    features: '常绿灌木，花单生叶腋，乳黄色，花瓣肉质，苞片宿存。',
    flowerLanguage: '含蓄、矜持、庄重。',
    careTips: '喜半阴湿润，怕强光直射，春季需及时修剪过密枝。',
    distribution: '原产中国华南，长江流域以南庭院常见。',
    funFact: '含笑因香气独特又被称为“香蕉花”，花苞能熏香整间房。',
    synonyms: ['含笑花', '香蕉花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/hanxiao.jpg', enabled: true
  },
  {
    id: 'yumeiren', cnName: '虞美人', latinName: 'Papaver rhoeas', family: '罂粟科', genus: '罂粟属',
    rarity: 'common', bloomSeasons: ['春', '夏'], colors: ['红', '粉', '白'],
    description: '薄如蝉翼的丽春花，风一吹便轻轻颤动，娇弱又倔强。',
    features: '花单生茎顶，花瓣 4 枚薄而皱，茎叶被毛，全株有乳汁。',
    flowerLanguage: '安慰、遗忘、生死离别。',
    careTips: '喜光耐寒，直根忌移栽，播种后不可随意移苗。',
    distribution: '原产欧洲，中国各地庭园栽培。',
    funFact: '虞美人名字来自项羽虞姬的传说，每年虞姬墓前开花如血。',
    synonyms: ['丽春花', '赛牡丹', '满园春'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/yumeiren.jpg', enabled: true
  },
  {
    id: 'xiuqiuhua', cnName: '绣球花', latinName: 'Hydrangea macrophylla', family: '绣球花科', genus: '绣球属',
    rarity: 'rare', bloomSeasons: ['夏'], colors: ['蓝', '紫', '粉', '白'],
    description: '一团团“无尽夏”，花色随土壤酸碱而变，梦幻感十足。',
    features: '伞房花序呈球形，边缘为不育花，土壤酸性偏蓝、碱性偏粉。',
    flowerLanguage: '希望、美满、团聚、浪漫。',
    careTips: '喜半阴湿润，调蓝可在花前施用硫酸铝，注意勿误食。',
    distribution: '原产中国及日本，长江流域及以南园林广植。',
    funFact: '日本镰仓的明月院与杭州临平公园都是著名绣球观赏地。',
    synonyms: ['绣球', '八仙花', '紫阳花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/xiuqiuhua.jpg', enabled: true
  },
  {
    id: 'dingxiang', cnName: '丁香', latinName: 'Syringa oblata', family: '木犀科', genus: '丁香属',
    rarity: 'rare', bloomSeasons: ['春', '夏'], colors: ['紫', '白'],
    description: '结着愁怨的紫丁香，花序繁密，香气清远，是北国春色代表。',
    features: '落叶灌木或小乔木，圆锥花序，花冠漏斗状，叶对生心形。',
    flowerLanguage: '纯真、谦逊、忧愁思念。',
    careTips: '喜光耐寒耐旱，花期后及时剪除残花序。',
    distribution: '原产中国华北，哈尔滨丁香满城，被誉为市花。',
    funFact: '丁香花有紫色与白色之分，也有重瓣品种，花药颜色因品种而异。',
    synonyms: ['紫丁香', '丁香花', '百结'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/dingxiang.jpg', enabled: true
  },
  {
    id: 'lingxiao', cnName: '凌霄', latinName: 'Campsis grandiflora', family: '紫葳科', genus: '凌霄属',
    rarity: 'common', bloomSeasons: ['夏', '秋'], colors: ['橙', '红'],
    description: '攀援而上的橙红喇叭花，凌云直上，是墙头檐角的盛夏风景。',
    features: '落叶藤本，气生根攀援，花冠漏斗状橙红色，聚伞花序。',
    flowerLanguage: '慈母之爱、敬佩、声誉。',
    careTips: '喜光耐旱，攀爬能力强，需定期修剪防疯长。',
    distribution: '原产中国中部，南北各省庭园常见。',
    funFact: '凌霄花期可达数月，古诗“披云似有凌云志”正是形容它的攀援之姿。',
    synonyms: ['凌霄花', '紫葳'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/lingxiao.jpg', enabled: true
  },
  {
    id: 'tanhua', cnName: '昙花', latinName: 'Epiphyllum oxypetalum', family: '仙人掌科', genus: '昙花属',
    rarity: 'legendary', bloomSeasons: ['夏', '秋'], colors: ['白'],
    description: '月下美人，花开仅数小时，一生一现，珍贵又浪漫。',
    features: '叶状茎扁平肉质，花大洁白生于茎缘，夜里开放凌晨闭合。',
    flowerLanguage: '刹那的美丽、永恒的瞬间。',
    careTips: '喜温暖半阴，花期前控水增光，现蕾后勿移动花盆。',
    distribution: '原产墨西哥及中美洲，中国各地盆栽。',
    funFact: '“昙花一现”的成语正是出自它的夜间短花期，盛放仅约 4 小时。',
    synonyms: ['月下美人', '韦陀花'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/tanhua.jpg', enabled: true
  },
  {
    id: 'xuelian', cnName: '雪莲', latinName: 'Saussurea involucrata', family: '菊科', genus: '风毛菊属',
    rarity: 'legendary', bloomSeasons: ['夏'], colors: ['白', '紫'],
    description: '雪线之上的“高山女神”，身披绒毛傲立冰雪，神秘而珍贵。',
    features: '植株被厚绵毛，苞叶层层包被花序，形似莲花，生长于高海拔流石坡。',
    flowerLanguage: '纯洁、坚韧、高尚。',
    careTips: '原生高山植物，人工栽培难度高，勿乱采野生植株。',
    distribution: '中国新疆天山、昆仑山等高海拔地区。',
    funFact: '天山雪莲是国家二级保护植物，神话里的“起死回生草”实为以讹传讹。',
    synonyms: ['天山雪莲'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/xuelian.jpg', enabled: true
  },
  {
    id: 'zijing', cnName: '紫荆', latinName: 'Cercis chinensis', family: '豆科', genus: '紫荆属',
    rarity: 'common', bloomSeasons: ['春'], colors: ['紫红'],
    description: '老干开花满枝紫红，花密如簇，先花后叶，热烈而团圆。',
    features: '落叶灌木，花假蝶形紫红色簇生老枝，荚果扁平，叶心形。',
    flowerLanguage: '家庭和美、骨肉情深、故园之思。',
    careTips: '喜光耐旱，忌水涝，花后修剪过密枝。',
    distribution: '原产中国，华北、华中、华南均有栽培。',
    funFact: '香港市花“洋紫荆”与中国紫荆是不同物种，别弄混啦。',
    synonyms: ['满条红'], illustrationFileID: 'cloud://cloud1-d2gckznjh68263f38.636c-cloud1-d2gckznjh68263f38-1465813845/assets/species/zijing.jpg', enabled: true
  }
];
